
title: Curriculum Vitae
url: 'https://cookiecrumbles.github.io/cv'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3 groen
#style: styles-4 paars
#style: styles-5 oranje
# style: styles-6 grijs


#Profile information
name: Kristof Stroobants
tagline: Windows System Administrator
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kristofstroobants@gmail.com
website: cookiecrumbles.github.io #do not add http://
linkedin: kristof-stroobants-1220106
github: CookieCrumbles
twitter: 'CoekieCrumbles'

#Update all the sections by editing the files inside _includes folder.
